baseurl: '/'
permalink: pretty
title: 'Film SF Alliance'
image: "assets/img/logo-shapes.svg"

logo:
  mobile: "assets/img/logo-shapes.svg"
  mobile_height: "50px"
  mobile_width: "50px"
  desktop: "assets/img/logo-text.svg"
  desktop_height: "30px"
  desktop_width: "150px"

collections:
  team:
    output: true
